### ISSUE TITLE
Comfyui Basic Primitive Nodes are Loading with NaN/null whilst having crystools-save enabled 

### ISSUE THREAD

**Issue by barleycoding** [crystian/ComfyUI-Crystools-save#1]
**Describe the bug**  
If you load any workflow containing primitive nodes it doesnt load correctly 

**To Reproduce**  

Load any Workflow containing a basic primitive Node 

**Expected behavior**  
Primitive Node should load correctly 

**Versions:**  
v1.10

windows 10 and windows 11

The Workflows with Primitive Node saved using crysstools-save load without a problem on comfyui installations without crystools-save

**Comment by crystian** [comment]
I'll check to night; thanks for your feedback
btw, have you updated everything?

**Comment by crystian** [comment]
done, can you update and try again please? @barleycoding

**Comment by barleycoding** [comment]
Everything was updated at the time. I just tested after the fix and everything works.
 I'll let you know if I discover something else. 
 
 Thanks for writing Crystools, it's a great and an essential Add-on to have.

**Comment by barleycoding** [comment]
After some testing , i ran into the same issue .

If a primitive Node is connected with a reroute it brakes again.

**Comment by crystian** [comment]
It is so strange. Do you have the latest version? 
1.1.3 (on custom_nodes\crystools-save\version)
and remember to push a lot of F5! hehe

**Comment by barleycoding** [comment]
I do have the lastet version.

If i connect a primitive node direclty to the input . it works fine.

Only if theres a reroute node  in between the primitive node and the input , than it brakes again.

**Comment by crystian** [comment]
I'll check @barleycoding

**Comment by crystian** [comment]
I fixed it. Can you test it (1.1.4), please?
It's a hack. There are race conditions when drawing.
@barleycoding

**Comment by barleycoding** [comment]
I tested 1.1.4
It is fixed.

Ill let you know if i discover something else.
