### ISSUE TITLE
Request for Adding Variable Support in Custom Workflow File Names

### ISSUE THREAD

**Issue by BigUncle** [crystian/ComfyUI-Crystools-save#2]
**Is your feature request related to a problem? Please describe.**
Firstly, I want to express my gratitude for providing such an excellent plugin. Currently, users can't use dynamic elements like dates when saving custom workflow files, limiting their ability to create filenames based on specific criteria or timestamps.

**Describe the solution you'd like**
I'd like the project to support variables in custom workflow filenames, allowing users to automatically generate values like the current date, like `%date:yyyy-MM-dd%_workflow` or `workdir/%date:yyyy-MM-dd-hhmmss%` or other something.

**Describe alternatives you've considered**
Users might manually update filenames, but this is time-consuming and error-prone.

**Additional context**
This enhancement would improve user flexibility and convenience, especially for those reliant on automated workflows.

![image (2)](https://github.com/crystian/ComfyUI-Crystools-save/assets/9360607/ea8d4987-ba8e-43f4-87cd-9ad92d1947ed)

**Comment by crystian** [comment]
I'll do next week (I hope!)

**Comment by crystian** [comment]
Sounds good but comfy change the manager, so, may deprecate this node... i'm not sure

**Comment by crystian** [comment]
you can use: https://github.com/HECer/ComfyUI-FilePathCreator
